title = "akku's website"
copyright = "-akku-"
languageCode = 'ja-jp'
timeZone = "Asia/Tokyo"
hasCJKLanguage = true

theme = "hugo-bearhouse"
enableRobotsTXT = true

[permalinks]
  blog = "/blog/:contentbasename/"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 5

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 10

  [[menus.main]]
    name = 'Works'
    pageRef = '/works'
    weight = 15

  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 20

  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 25

[params]
  description = "akku's website"
  favicon = "images/favicon.png"
  madeWith = "made with [Bear House](https://github.com/akku1139/hugo-bearhouse.git)"

  [params.author]
    name = "-akku-"
    # email = "root@akku.dedyn.io"

  [params.social]
    twitter = "akku1139"

# https://budougumi0617.github.io/2020/03/10/hugo-render-raw-html/
# https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      #unsafe = true
